### ISSUE TITLE
Is there any chance to export training-mode from SIR model?

### ISSUE THREAD

**Issue by ramonfontes** [cidacslab/Mathematical-and-Statistical-Modeling-of-COVID19-in-Brazil#2]
and then load the training for a new prediction?

**Comment by Julian-sun** [comment]
This is quit complicated to do with an SIR model, with the parameters not changing over time. 
The model SIR has 2 parameters, one is the transmission rate (beta) and other the infectious period (gamma). However, you can take a training set that is completely independent of the remaining series, just because the course of the dynamic had changed (caused by the transmission rate for instance).  We show down an example of that, the dashed line represent the SIR (the model is not exactly with SIR, but can easily be applied to) with parameters not changing on time and the full line with the transmission rate changing. It is a problem to think about and we didn't work with it here... 

![image](https://user-images.githubusercontent.com/45834356/83290354-e9673480-a1bc-11ea-87b6-b77af51d93ec.png)


Is that what do you mean? Did I answer your question?

**Comment by ramonfontes** [comment]
As we know the model does not yield the same results if we run it twice and I was not interested in save the results in a csv file. That's why I was looking for a way to save the model and then load it. I'm using Colab and your SIR model at https://github.com/covidba/covid to make some predictions.

Btw, I had to apply a patch because [logging.disable()](https://github.com/cidacslab/Mathematical-and-Statistical-Modeling-of-COVID19-in-Brazil/blob/master/main/modelos.py#L27) didn't work in Colab. The [SIR tutorial](https://github.com/cidacslab/Mathematical-and-Statistical-Modeling-of-COVID19-in-Brazil/blob/master/tutorials/SIR.ipynb) didn't work too, but I just noticed some new changes within the file.

**Comment by Julian-sun** [comment]
Hey Ramon, you just need to save the parameters and then use it for your purpose.

**Comment by ramonfontes** [comment]
Hi @Julian-sun,

Which parameters did you mean? Would be [these ones](https://github.com/cidacslab/Mathematical-and-Statistical-Modeling-of-COVID19-in-Brazil/blob/b027520ccb948bfd982b31a9148430a59e582326/main/modelos.py#L217) by any chance? What I'm doing now is to hide past days and only consider the future as you can see below:

![](https://drive.google.com/uc?export=view&id=1AwNiHHo8zKp7q2p53o5Lgb1rBsJ8YXdz)

Perhaps this fits better my goals.

**Comment by rafael-veiga** [comment]
> and then load the training for a new prediction?

Yes! you can save your models and made predictions

`import modelos as md
import _pickle as pk


x = [1,2,3,4,5,6,7,8,9,10]

y = [1,2,2,2,2,3,6,10,13,15]

N_population = 20000

modelo = md.SIR(N_population)
#fitting train model
modelo.fit(x,y)

modelo.plot('test')
modelo.optimize=None
# save model
file = open('model1.dat','wb')
pk.dump(modelo,file)
file.close()
# load model
file =open('model1.dat','rb')
modelo2 = pk.load( file )
file.close()

#test model
x2 = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
ypred =modelo.predict(x2)`

**Comment by ramonfontes** [comment]
Yes, it works like a charm! Thanks a lot! ;)
